name: Docker registry

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build and publish docker container
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com

      - name: Build :latest
        if: success()
        run: docker build -t docker.pkg.github.com/egorhenek/edm_su_api/api:latest .
        
      - name: Push to docker hub :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push docker.pkg.github.com/egorhenek/edm_su_api/api:latest
          
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd www
            docker-compose -f docker-compose.prod.yml pull api
            docker-compose -f docker-compose.prod.yml run api alembic upgrade head
            docker-compose -f docker-compose.prod.yml up --no-deps -d api worker-beat worker-scanner worker-default
