name: Lint

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Setup python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.9
      
      - uses: actions/checkout@v2

      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
